# CIS 443-01 Exam 2 Notebook
## 100 pts.
## Directions
1. Answer the question in the cell provided.
1. When finished, save your work, close the Jupyter Lab file, and Shut Down Jupyter Lab. You will upload this Jupyter Notebook file as your submission to Question 1 in Exam 2 in Blackboard.
1. Be sure to keep an unaltered version of this file just in case anything goes wrong in Blackboard. If you aren't working from your own computer, upload a copy to OneDrive or other cloud storage and do not modify it.


# Concept Questions

### Question 1

How does a list differ from a Numpy Array? Make sure to address data types and copying.

### Question 2

Why do Pandas Series+Dataframes, and Numpy Arrays have so much in common? What underlying language do they get this functionality from?

### Question 3

What flat file format did we discuss for handling data transfers into our scripts? Why was it better than .txt data? What was a drawback?

### Question 4

What is meant by sentiment of a body of text? What about polarity? What was the scale (of the algorithm that we used) of each, and what did the scale mean?

### Question 5

Describe the difference between a shallow copy of a collection and a deep copy.

### Question 6

What were the 4 code blocks of exception managment? Explain the role of each. Which one is typically repeated within one try structure?

### Question 7

If we predominantly use CSV files for transmitting information in flat files, what was the use case for JSON? What does it have in common with XML?

### Question 8

A linear regression model is rooted in `y=mx+b` - explain each part of this equation, in terms of relevance to linear regression and real world meaning.

### Question 9

Explain what the r^2 value and the p value mean in terms of a data model, such as linear regression. What is a 'good' value for each?

### Question 10

Explain the 4 set operators: union, difference, intersect, and symmetric difference. 

### Question 11

Explain a real world use for natural language process, anything that you choose. 

# Code Fragments

### Problem 1
Write a Python code fragment in the code cell below that uses pandas to load the csv file which was attached to the exam. Print the head of the dataframe. 



In [5]:
import pandas as pd
file = pd.read_csv('cust.csv')
print(file.head())

   Index      Customer Id First Name Last Name  \
0      1  DD37Cf93aecA6Dc     Sheryl    Baxter   
1      2  1Ef7b82A4CAAD10    Preston    Lozano   
2      3  6F94879bDAfE5a6        Roy     Berry   
3      4  5Cef8BFA16c5e3c      Linda     Olsen   
4      5  053d585Ab6b3159     Joanna    Bender   

                           Company               City  \
0                  Rasmussen Group       East Leonard   
1                      Vega-Gentry  East Jimmychester   
2                    Murillo-Perry      Isabelborough   
3  Dominguez, Mcmillan and Donovan         Bensonview   
4         Martin, Lang and Andrade     West Priscilla   

                      Country                 Phone 1                Phone 2  \
0                       Chile            229.077.5154       397.884.0519x718   
1                    Djibouti              5153435776       686-620-1820x944   
2         Antigua and Barbuda         +1-539-402-0259    (496)978-3969x58947   
3          Dominican Republic  001-8

### Problem 2
Create a blob for the included string, and display the sentiment analysis for the text. 

In [29]:
import textblob as tb

sample_text = '''O Captain! my Captain! our fearful trip is done,
The ship has weather’d every rack, the prize we sought is won,
The port is near, the bells I hear, the people all exulting,
While follow eyes the steady keel, the vessel grim and daring;'''

sample_blob = tb.TextBlob(sample_text)
sample_sentiment = tb.Sentiment(sample_blob)

print(f"Sentiment Value: {sample_sentiment}")


ModuleNotFoundError: No module named 'textblob'

### Problem 3
Write a Python code fragment in the code cell below that catches `ValueError` and prints out a corresponding message to the user. Have it print out 'Application Finished' regardless of whether this exception occured or not, using the correct suite.

In [25]:
#your code here
try:
    bad_function()
except ValueError:
    print("Application Failed")
else:
    print("Application Succeeded")
finally:
    print("Application Finished")

#my code here
def bad_function():
    return int('ABC')

Application Failed
Application Finished


### Problem 4
Use arange and reshape to create a 5-by-4 ndarray containing the numbers 1–20 (inclusive of both endpoints). Use broadcasting to perform each of the following operations on the original array creating a new ndarray and printing its contents: (2 pts. each)

    Use arange and reshape to create a 5-by-4 ndarray containing the numbers 1–20 (inclusive of both endpoints). Print the original array.
    Use broadcasting to subtract 27 to every element of the original array. Print the resulting array.
    Use broadcasting to multiply every element of the original array by 14. Print the resulting array.

In [47]:
import numpy as np
shapeArray = np.arange(1, 20+1).reshape(5, 4)
print(shapeArray)
print(shapeArray - 27)
print(shapeArray * 14)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[-26 -25 -24 -23]
 [-22 -21 -20 -19]
 [-18 -17 -16 -15]
 [-14 -13 -12 -11]
 [-10  -9  -8  -7]]
[[ 14  28  42  56]
 [ 70  84  98 112]
 [126 140 154 168]
 [182 196 210 224]
 [238 252 266 280]]


### Problem 5
Write a Python code fragment in the code cell below that inputs a line of text from the user, tokenizes the text using period characters as delimiters and outputs the tokens in reverse order. Use `'. '` sequences as delimiters. For example, "Hello. Goodbye." becomes "Goodbye. Hello."

In [59]:
user = input("Please enter a line of text.")
user.split(' ')
print(user[::-1])

Please enter a line of text. a. b. c.


.c .b .a


# Coding Problem

Write a Python code solution in the code cell below that performs a linear regression against the preimported data. Use the `GrLivArea` to predict `SalePrice`. Display and explain the r^2 and p values for the Living Area vs Price regression.


In [108]:
# Do not modify the code below
import pandas as pd
from scipy import stats
data = pd.read_csv(r'https://raw.githubusercontent.com/laxmimerit/All-CSV-ML-Data-Files-Download/refs/heads/master/houseprice.csv')
reduced_data = data[['GrLivArea', 'SalePrice']]
reduced_data

#your code here
data_linreg = stats.linregress(reduced_data['GrLivArea'], reduced_data['SalePrice'])
data_pSq = data_linreg.rvalue * data_linreg.rvalue
print(f"R Squared: {data_pSq} \nP Value: {data_linreg.pvalue}\n")
datafr = pd.DataFrame(reduced_data)
datafr['Predicted SalePrice'] = datafr['GrLivArea'] * data_linreg.slope + data_linreg.intercept
print(datafr)

R Squared: 0.5021486502718042 
P Value: 4.518033646776791e-223

      GrLivArea  SalePrice  Predicted SalePrice
0          1710     208500        201761.939688
1          1262     181500        153767.538871
2          1786     223500        209903.846969
3          1717     140000        202511.852201
4          2198     250000        254041.554863
...         ...        ...                  ...
1455       1647     175000        195012.727073
1456       2073     210000        240650.259993
1457       2340     266500        269254.065837
1458       1078     142125        134055.552822
1459       1256     147500        153124.756718

[1460 rows x 3 columns]


Be sure to save and exit your Jupyter Notebook and Shutdown Jupyter Lab (from the __File__ menu) if using Ananconda before you submit your notebook on Blackboard for grading. If using Colab, be sure to Download (from the __File__ menu) back to your local file system before submitting to Blackboard.
Make sure you don't submit the empty starting notebook by accident.